project:
  type: website

website:
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  navbar:
    search: true
    background: '#1a2b48'
    left:
      - text: Home
        href: index.html
    right:
      - text: About
      - menu:
          - text: About
            href: about/index.qmd
          - text: Committes
            href: committes/index.qmd
          - text: Travel
            href: travel/index.qmd
      - text: Apply
        href: index.html#apply
      - text: Registration
        href: registration/index.qmd
      - text: Speakers
        href: index.html#speakers
      - text: Program
        menu:
          - text: Schedule
            href: program/index.qmd
          - text: Workshops
            href: workshop/index.qmd
          - text: Panels
            href: panels/index.qmd
      - text: Participants
        href: participants/index.qmd

format:
  html:
    backgroundcolor: "#F8F9FA" # https://www.figma.com/colors/
    theme: [styles.scss] # https://quarto.org/docs/output-formats/html-themes.html
